### ISSUE TITLE
Reading RangeAndBearingSensor

### ISSUE THREAD

**Issue by tylerferrara** [NESTLab/argos_bridge#1]
## Background
The Khepera robots publish line-of-site data to individual ros topics. For example:
```zsh
$ rostopic list
/kheperaiv_ros_10/lineOfSight
/kheperaiv_ros_20/lineOfSight
/kheperaiv_ros_30/lineOfSight
```
These topics publish losList.msg which holds a list of robot names it can see.
```zsh
# losList.msg
Header header
int32 n
los[] robots
```
```zsh
# los.msg
string robotName
```

This logic is found in the kheperaiv_ros.cpp file within the [publishLineOfSite](https://github.com/NESTLab/argos_bridge/blob/346576a9327380b3e40a5de484563626d958e1ac/plugin/kheperaiv_ros/kheperaiv_ros.cpp#L140-L160) function.

We initiate this behavior by running a .argos simulation file within argos_bridge/argos_worlds
```zsh
# First run roscore
$ roscore
```
```zsh
# Start the simulation
$ argos3 -c src/coms/argos_bridge/argo_worlds/multi_robots.argos
```

We can then start out simulation within the desktop environment (http://localhost:8080/vnc.html) by pressing the Big Play Button.

<img width="1436" alt="Screen Shot 2022-02-22 at 2 35 55 PM" src="https://user-images.githubusercontent.com/20875599/155206032-aee01dd7-1bca-444c-82d6-8b75009ca2a3.png">

You'll know it's started when purple lines appear, showing the robot's line-of-site sensors at work.

## Issue
When running the argos3 simulation, as mentioned above, the line-of-site messages are malformed:
```zsh
$ rostopic echo /kheperaiv_ros_20/lineOfSight
header:
  seq: 0
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "\0\0\0\0\0\0\0\0\0\0"
---
[ERROR] [1645558773.316301]: Characters replaced when decoding message argos_bridge/losList (will print only once): 'utf-8' codec can't decode byte 0xa0 in position 3: invalid start byte
header:
  seq: 1
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "\0\0\x10\uFFFD\uFFFD\uFAAA\0\0"
---
header:
  seq: 2
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "\0\0\x10\uFFFD\uFFFD\uFAAA\0\0"
```

The robotName is not formatted as a String. More precisely, the [publishLineOfSite](https://github.com/NESTLab/argos_bridge/blob/346576a9327380b3e40a5de484563626d958e1ac/plugin/kheperaiv_ros/kheperaiv_ros.cpp#L140-L160) function is not publishing the correct data from the `CCI_RangeAndBearingSensor`.

A desirable output would be as follows:
```
$ rostopic echo /kheperaiv_ros_20/lineOfSight
header:
  seq: 0
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: ""
---
header:
  seq: 1
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "kheperaiv_ros_20"
---
header:
  seq: 2
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "kheperaiv_ros_20"
```

**Comment by tylerferrara** [comment]
Blocking https://github.com/NESTLab/coms/issues/4 and https://github.com/NESTLab/2122_MultiDroneIndoorSLAM/issues/15

**Comment by tylerferrara** [comment]
Looking for help
@nikopoulospet @ilpincy

**Comment by ilpincy** [comment]
How can I help? From what you reported, this seems to be simply a malformed message issue. Am I missing something?

**Comment by tylerferrara** [comment]
SOLVED! 🎉
[This forum post](https://www.argos-sim.info/forum/viewtopic.php?t=201) demystified how to send data over the CCI_RangeAndBearingSensor

Apparently we are sending [ids in this line](https://github.com/NESTLab/argos_bridge/blob/346576a9327380b3e40a5de484563626d958e1ac/plugin/kheperaiv_ros/kheperaiv_ros.cpp#L142-L146) by copying each byte directly This has undesirable consequences for a variety of reasons. However, if we copy the contents of `std::string id` to a `argos::CByteArray`, we can send it right over the actuator. When receiving these messages, we can simply convert back to `std::string `.

Proof:
```zsh
$ rostopic echo /kheperaiv_ros_20/lineOfSight
header:
  seq: 0
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "\0\0\0\0\0\0\0\0\0\0"
---
header:
  seq: 1
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "kheperaiv_"
---
header:
  seq: 2
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "kheperaiv_"
---
header:
  seq: 3
  stamp:
    secs: 0
    nsecs:         0
  frame_id: ''
n: 1
robots:
  -
    robotName: "kheperaiv_"
```

NOTE: Only 10 bytes can be sent over the range and bearing sensor.
